### ISSUE TITLE
Add formatted logging methods

### ISSUE THREAD

**Issue by clandry94** [ivahaev/go-logger#1]
Hi, I really enjoy your logging library. Have you considered adding methods such as 
`logger.Infof()` et. al. to allow formatted logs? This would let users do something like
```
output := "Some output of an application"
logger.Infof("Here is some log %v", output") 
```
If you'd like I can put a PR together!

**Comment by ivahaev** [comment]
Hi,
I'm really surprised :). I use this logger for debug purpose only. But I can add formatted output, or you can create PR for it :)
